# The way this works is the following:
#
# - create-release job runs purely to initialize the GitHub release itself
# and to output upload_url for the following job.
#
# - build-release job runs only once create-release is finished. It gets
# the release upload URL from create-release job outputs, then builds
# the release executables for each supported platform and attaches them
# as release assets to the previously created release.
#
# Reference:
# - https://eugene-babichenko.github.io/blog/2020/05/09/github-actions-cross-platform-auto-releases/
#
# Currently this workflow only ever creates drafts; the draft should be checked
# and then released manually.

name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: create_release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          # draft: ${{ github.event_name == 'workflow_dispatch' }}
          draft: true
          prerelease: false

  build-release:
    name: build-release
    needs: create-release
    runs-on: ubuntu-latest
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
      BANDWHICH_GEN_DIR: assets
      PKGDIR: github-actions-pkg
    strategy:
      matrix:
        build: [linux-x64-gnu]
        include:
          - build: linux-x64-gnu
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            cargo: cargo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu

      - name: Build release binary
        shell: bash
        env:
          RUSTFLAGS: "-C strip=symbols"
        run: |
          mkdir -p "$BANDWHICH_GEN_DIR"
          cargo build --verbose --release --target x86_64-unknown-linux-gnu

      - name: Collect build artifacts
        shell: bash
        run: |
          mkdir "$PKGDIR"
          mv "target/x86_64-unknown-linux-gnu/release/bandwhich" "$PKGDIR"
          mv "$BANDWHICH_GEN_DIR" "$PKGDIR"

      - name: Tar release
        working-directory: ${{ env.PKGDIR }}
        run: tar cvfz bandwhich-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz *

      - name: Upload release archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ env.PKGDIR }}/bandwhich-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz
          asset_name: bandwhich-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz
          asset_content_type: application/octet-stream
